//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Testing_LastProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fakulteler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fakulteler()
        {
            this.Bolumlers = new HashSet<Bolumler>();
        }

        public override string ToString()
        {
            return FakulteId.ToString();
        }

        public int FakulteId { get; set; }
        public string FakulteAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bolumler> Bolumlers { get; set; }
    }
}
