//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Testing_LastProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Role
    {
        public int KullaniciRoleId { get; set; }
        public int KullaniciId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Roller Roller { get; set; }
    }
}
