//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Testing_LastProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaFakulteBolum
    {
        public int OdaFakulteBolumId { get; set; }
        public int OdaId { get; set; }
        public int BolumId { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Odalar Odalar { get; set; }
    }
}
